// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhqijmrxfzcnkfxjmnpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocWlqbXJ4ZnpjbmtmeGptbnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTg2MTIsImV4cCI6MjA2MTA5NDYxMn0.h-QNFojp69wjDfFIOvdDiaPCvj7HwKRaRfc4zihxECQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);